Code for generating the Stochastic Block Model (SBM) graph employed in the Source Localization and Finite Time Consensus experiments.

## Imports

In [1]:
import pickle
import Utils.graphTools as graphTools

## Data Parameters

In [3]:
graphType = 'SBM' 
nNodes = 50 # Number of nodes
nClasses = 5 #5 # Number of classes (i.e. number of communities)
graphOptions = {} # Dictionary of options to pass to the graphTools.createGraph function
graphOptions['nCommunities'] = nClasses # Number of communities
graphOptions['probIntra'] = 0.8 # Probability of drawing edges intra communities
graphOptions['probInter'] = 0.1 # Probability of drawing edges inter communities

## Graphs Creation

In [4]:
allGraphs = []
allAdjMatrix = []

for i in range(0, 7):
    G = graphTools.Graph(graphType, nNodes, graphOptions)
    allGraphs.append(G)
    allAdjMatrix.append(G.W)   

print(G)
print(G.W)

Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
Tipul matricei W este <class 'numpy.ndarray'>
Dimensiunile sunt f(50, 50)
[[0. 1. 1. ... 1. 1. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 1. 0. 0.]
 ...
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [5]:
with open('graphs', 'wb') as fp:
    pickle.dump(allGraphs, fp)